### ISSUE TITLE
Image loading issue

### ISSUE THREAD

**Issue by SharifTanvir** [KlausSchaefers/luisa-vue2-starter#1]
I have used some png image as background image but  they are not showing in browser while i build a prototype. 
I am having below error in my console: 

`Quant2Flat.fixNames() > Dubplicate name of element 'Box 1_1_2' in screen 'Home'`

**Comment by SharifTanvir** [comment]
You are using background image url as `public/img/quant-project-id/image-name.png`
but while it is downloading images are saved as `public/img/image-name.png`

That's why images are not loading. What's your opinion for this ?

**Comment by KlausSchaefers** [comment]
Hi, this is indeed a bug. You are using the quant-ux cli? The simplest way to fix is to set the image path to the correct version

```
  config: {
          imageFolder: '/public/img/quant-project-id/'
     
        }
```

**Comment by KlausSchaefers** [comment]
I will fix the issue in the CLI
