### ISSUE TITLE
Cannot make Rest call with auth token

### ISSUE THREAD

**Issue by zcpp** [KlausSchaefers/luisa-vue2-starter#3]
## Version
```
"luisa-vue": "^2.0.9"
"vue": "^2.6.11"
```

## Usage
```
<Luisa :design="app" :config="config" :showDebug="true"/>
...
...
import Luisa from 'luisa-vue'
Vue.use(Luisa);
```
The "app" is loaded from a quant-ux exported json file

## Problem
A Rest request with bearer token auth is in the app. The page can be rendered, but failed to make the Rest call because token was not passed in the request.
![1637661484(1)](https://user-images.githubusercontent.com/5620097/143003956-935ecd81-938f-4b69-b7dc-93e742b2c74a.png)
![1637661517(1)](https://user-images.githubusercontent.com/5620097/143004049-efeb2be9-6542-4165-8bfa-f57fd00b3ee7.png)

**Comment by KlausSchaefers** [comment]
Can you share the project with me? klaus.schaefers@quant-ux.com

**Comment by KlausSchaefers** [comment]
Hi, there might have been a bug. Can you update to 

```
nom install luisa-vue@2.0.11
```

**Comment by zcpp** [comment]
Hi @KlausSchaefers , updating to luisa-vue@2.0.11 solved the problem. Thanks!
