### ISSUE TITLE
Data binding doesn't work

### ISSUE THREAD

**Issue by zcpp** [KlausSchaefers/luisa-vue2-starter#4]
## Version
```
"luisa-vue": "^2.0.9"
"vue": "^2.6.11"
```

## Usage
```
<Luisa :design="app" :config="config" :showDebug="true"/>
...
...
import Luisa from 'luisa-vue'
Vue.use(Luisa);
```
The "app" is loaded from a quant-ux exported json file. The app json file shows the version is **2.1**.
In the app, there are a camera and camera-image components. They are sharing same data "myimage".

## Problem
The page can be loaded. The camera button works - can open file choosing dialog from PC or launch camera on mobile phone.
After choosing a picture or taking a phone, the camera image box doesn't show the picture. The app functions work well in quant-ux designing website.
![1637662152(1)](https://user-images.githubusercontent.com/5620097/143005569-9f86435a-9523-4ffc-b743-13732231109d.png)

**Comment by KlausSchaefers** [comment]
Hi,

Did you add the "myimage" variable to the view model? The following code works for me.

```vue
<template>
  <div class="home">
    <Luisa design="a2aa10amGCywEpVXkeoHkpDKYPrvy4lFoNryqx9MEXB3byj66Q0yhaF9ZjU2" v-model="viewModel" :config="config"/>
  </div>
</template>
<style lang="scss">

</style>

<script>
import Vue from "vue";
import Luisa from 'luisa-vue'
Vue.use(Luisa);

export default {
  name: 'Home',
  data: function () {
    return {
      viewModel: {
        myimage: 2     
      },
      config: {
        debug: {
          logLevel: 5
        }
      }
    }
  },
  components: {
  },
  methods: {
  }
}
</script>`
``

 If this does not fix the issue, can you please quant-ux project (Menu > Export > Zip)?

**Comment by zcpp** [comment]
@KlausSchaefers thanks for your reply. Adding view-Model works.
